### PR TITLE
Bump egui and winit versions, fixed breaking changes

### PR DESCRIPTION
**Pull request by Wicpar**

### CODE REVIEW

**Comment by hasenbanck** [comment]
LGTM. I will release a new version at the end of the week.

**Comment by Wicpar** [comment]
i still haven't gotten it to work, the changes should be fine but inputs are not processed in my app (it may be my app that is bugged)

**Comment by Wicpar** [comment]
it looks like events are not properly taken, it makes no sense.

**Comment by Wicpar** [comment]
alright i think it is because there is no redraw on cursor position change. please test on your side too before release, sorry for the pr being incomplete, i did not expect it to be merged so fast

**Comment by Wicpar** [comment]
i fixed it, it is indeed a bug with my implementation and not the PR

**Comment by Wicpar** [comment]
Thanks for the fast merge :)
one thing to note is that there is no info around the fact the application should request a redraw if there are pending events, maybe add a dedicated function ?

**Comment by hasenbanck** [comment]
Hi! Feel free to propose your solution in the form of a PR!

**Pull request merged**
